name: CI Main

on: [push, pull_request]

jobs:
  BuildLinuxClang:
    runs-on: ubuntu-latest
    container: jackd13/audioplugins:clang10

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: RunBuild
        run: Scripts/BuildLinux.sh
      - name: RunPluginval
        run: Scripts/PluginvalLinux.sh
      - uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: songbird-linux-clang
          path: Builds/LinuxMakefile/build/*.vst3

  BuildLinuxGCC:
    runs-on: ubuntu-latest
    container: jackd13/audioplugins:gcc10

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: RunBuild
        run: Scripts/BuildLinux.sh
      - name: RunPluginval
        run: Scripts/PluginvalLinux.sh
      - uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: songbird-linux-gcc
          path: Builds/LinuxMakefile/build/*.vst3

  BuildMacOS:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: RunBuild
        run: Scripts/BuildMacOS.sh
      - uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: songbird-macOS
          path: |
            ~/Library/Audio/Plug-Ins/VST3/*.vst3
            ~/Library/Audio/Plug-Ins/Components/*.component
