name: CI Main

on: [push, pull_request]

jobs:
  BuildClang:
    runs-on: ubuntu-latest
    container: jackd13/audioplugins:clang10

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: RunBuild
        run: Scripts/CIBuild.sh
      - name: RunPluginval
        run: Scripts/CIPluginval.sh

  BuildGCC:
    runs-on: ubuntu-latest
    container: jackd13/audioplugins:gcc10

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: RunBuild
        run: Scripts/CIBuild.sh
      - name: RunPluginval
        run: Scripts/CIPluginval.sh
